#!/usr/bin/env python3
"""
GCP Security Agent Setup Script
===============================

This script helps configure the security agent for your GCP project.
Run this before starting the application.
"""

import os
import sys
import json
import shutil
from pathlib import Path
from typing import Optional


def print_header():
    """Print setup header."""
    print("🔐 GCP Security Agent Setup")
    print("=" * 50)
    print()


def check_prerequisites():
    """Check if required tools are installed."""
    print("🔍 Checking prerequisites...")
    
    required_commands = ["gcloud", "python", "pip"]
    missing = []
    
    for cmd in required_commands:
        if not shutil.which(cmd):
            missing.append(cmd)
    
    if missing:
        print(f"❌ Missing required tools: {', '.join(missing)}")
        print()
        print("Please install:")
        if "gcloud" in missing:
            print("• Google Cloud CLI: https://cloud.google.com/sdk/docs/install")
        if "python" in missing:
            print("• Python 3.8+: https://python.org/downloads")
        if "pip" in missing:
            print("• pip: Usually comes with Python")
        return False
    
    print("✅ All prerequisites found")
    return True


def get_project_id() -> Optional[str]:
    """Get GCP project ID from user or gcloud."""
    print()
    print("📋 GCP Project Configuration")
    print("-" * 30)
    
    # Try to get from gcloud first
    try:
        import subprocess
        result = subprocess.run(
            ["gcloud", "config", "get-value", "project"],
            capture_output=True,
            text=True
        )
        if result.returncode == 0 and result.stdout.strip():
            current_project = result.stdout.strip()
            print(f"🔍 Current gcloud project: {current_project}")
            
            response = input(f"Use this project? (y/n) [y]: ").strip().lower()
            if response in ['', 'y', 'yes']:
                return current_project
    except Exception:
        pass
    
    # Get from user input
    while True:
        project_id = input("Enter your GCP Project ID: ").strip()
        if project_id:
            return project_id
        print("❌ Project ID cannot be empty")


def get_service_account_path() -> Optional[str]:
    """Get service account key file path."""
    print()
    print("🔑 Service Account Configuration")
    print("-" * 35)
    print("You need a service account key file with the following permissions:")
    print("• Cloud Asset Viewer")
    print("• Security Center Admin Viewer")
    print("• Storage Admin")
    print("• IAM Security Reviewer")
    print("• Recommender Viewer")
    print("• Secret Manager Viewer")
    print("• Monitoring Viewer")
    print()
    
    while True:
        key_path = input("Enter path to service account key file (.json): ").strip()
        if not key_path:
            print("❌ Path cannot be empty")
            continue
        
        # Expand user path
        key_path = os.path.expanduser(key_path)
        
        if not os.path.exists(key_path):
            print(f"❌ File not found: {key_path}")
            continue
        
        if not key_path.endswith('.json'):
            print("❌ File must be a .json file")
            continue
        
        # Validate JSON format
        try:
            with open(key_path, 'r') as f:
                data = json.load(f)
                if 'type' in data and data['type'] == 'service_account':
                    return os.path.abspath(key_path)
                else:
                    print("❌ File doesn't appear to be a service account key")
        except json.JSONDecodeError:
            print("❌ Invalid JSON file")
        except Exception as e:
            print(f"❌ Error reading file: {e}")


def create_env_file(project_id: str, service_account_path: str):
    """Create .env file with configuration."""
    print()
    print("📝 Creating .env file...")
    
    env_content = f"""# GCP Security Agent Configuration
# Generated by setup.py

# Google Cloud Configuration
GOOGLE_CLOUD_PROJECT={project_id}
GOOGLE_APPLICATION_CREDENTIALS={service_account_path}

# Vertex AI Configuration
VERTEX_AI_LOCATION=us-central1
VERTEX_AI_MODEL=gemini-2.0-flash

# Application URLs
BACKEND_URL=http://localhost:8000
FRONTEND_URL=http://localhost:8501
BACKEND_PORT=8000
FRONTEND_PORT=8501

# Database Configuration
DATABASE_PATH=cache/gcp_data.db
DATA_REFRESH_INTERVAL=1800

# Security Settings
RATE_LIMIT_CHAT=30
RATE_LIMIT_HEAVY=5
RATE_LIMIT_DEFAULT=100

# Features
ENABLE_RATE_LIMITING=true
ENABLE_INPUT_VALIDATION=true
ENABLE_MONITORING=true
ENABLE_BACKGROUND_REFRESH=true

# Logging
LOG_LEVEL=INFO
DEBUG_MODE=false
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print("✅ .env file created successfully")


def install_dependencies():
    """Install Python dependencies."""
    print()
    print("📦 Installing dependencies...")
    
    try:
        import subprocess
        result = subprocess.run([
            sys.executable, "-m", "pip", "install", "-r", "requirements.txt"
        ], capture_output=True, text=True)
        
        if result.returncode == 0:
            print("✅ Dependencies installed successfully")
            return True
        else:
            print(f"❌ Failed to install dependencies: {result.stderr}")
            return False
    except Exception as e:
        print(f"❌ Error installing dependencies: {e}")
        return False


def test_configuration(project_id: str):
    """Test the configuration."""
    print()
    print("🧪 Testing configuration...")
    
    # Test environment variables
    os.environ['GOOGLE_CLOUD_PROJECT'] = project_id
    
    try:
        # Test Google Cloud authentication
        from google.cloud import asset_v1
        client = asset_v1.AssetServiceClient()
        parent = f"projects/{project_id}"
        
        # This will fail if authentication is wrong
        request = asset_v1.ListAssetsRequest(parent=parent, page_size=1)
        list(client.list_assets(request=request))
        
        print("✅ Google Cloud authentication working")
        return True
        
    except Exception as e:
        print(f"❌ Configuration test failed: {e}")
        print()
        print("Common issues:")
        print("• Service account key file path is incorrect")
        print("• Service account doesn't have required permissions")
        print("• Project ID is incorrect")
        print("• APIs are not enabled in your project")
        return False


def print_next_steps():
    """Print next steps for the user."""
    print()
    print("🎉 Setup Complete!")
    print("=" * 20)
    print()
    print("Next steps:")
    print("1. Start the backend:  python run_backend.py")
    print("2. Start the frontend: python run_frontend.py")
    print("3. Open browser:       http://localhost:8501")
    print()
    print("📚 Documentation:")
    print("• Review docs/IAM_ANALYSIS_ARCHITECTURE.md for architecture details")
    print("• Use 'refresh data' in the frontend to populate cache")
    print("• View API docs at http://localhost:8000/docs")
    print()


def main():
    """Main setup function."""
    print_header()
    
    # Check prerequisites
    if not check_prerequisites():
        sys.exit(1)
    
    # Get configuration
    project_id = get_project_id()
    if not project_id:
        print("❌ Setup cancelled")
        sys.exit(1)
    
    service_account_path = get_service_account_path()
    if not service_account_path:
        print("❌ Setup cancelled")
        sys.exit(1)
    
    # Create configuration
    create_env_file(project_id, service_account_path)
    
    # Install dependencies
    if not install_dependencies():
        print("⚠️ Continue with manual dependency installation")
    
    # Test configuration
    test_configuration(project_id)
    
    # Print next steps
    print_next_steps()


if __name__ == "__main__":
    main()
