-- Cloud Logging Export to BigQuery - Analytics Queries
-- =====================================================
-- These queries work with Cloud Logging data exported to BigQuery.
-- They demonstrate what's POSSIBLE and what's MISSING compared to
-- the BigQuery Agent Analytics Plugin.
--
-- IMPORTANT: These queries are BEST-EFFORT because:
--   1. OTel logs don't capture token usage
--   2. OTel logs don't capture tool arguments/results
--   3. Log format may change, breaking queries
--   4. JSON parsing is fragile
--
-- Project: test-project-0728-467323
-- Dataset: cloud_logging_export
-- =====================================================


-- ============================================================================
-- SETUP: Understand the exported schema
-- ============================================================================

-- The exported logs have this structure (auto-generated by Cloud Logging):
-- - timestamp: TIMESTAMP
-- - logName: STRING (e.g., "projects/xxx/logs/adk-otel")
-- - severity: STRING (DEFAULT, INFO, WARNING, ERROR, etc.)
-- - textPayload: STRING (for simple text logs)
-- - jsonPayload: JSON (for structured logs)
-- - trace: STRING (trace ID)
-- - spanId: STRING
-- - resource: RECORD (type, labels)

-- View the raw exported data structure
SELECT *
FROM `test-project-0728-467323.cloud_logging_export.adk_otel_*`
LIMIT 5;


-- ============================================================================
-- 1. TOKEN USAGE ANALYSIS
-- ============================================================================
-- STATUS: NOT POSSIBLE
-- REASON: OTel spans do NOT capture token counts - this data is simply not
--         available in Cloud Logging exports.

-- WORKAROUND: None. Token usage requires the BigQuery Agent Analytics Plugin.

-- This query will return NULL for all token fields:
SELECT
  timestamp,
  -- These fields DON'T EXIST in OTel logs
  JSON_EXTRACT_SCALAR(jsonPayload, '$.usage.total') AS total_tokens,  -- NULL
  JSON_EXTRACT_SCALAR(jsonPayload, '$.usage.prompt') AS prompt_tokens,  -- NULL
  JSON_EXTRACT_SCALAR(jsonPayload, '$.usage.completion') AS completion_tokens  -- NULL
FROM `test-project-0728-467323.cloud_logging_export.adk_otel_*`
WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
LIMIT 10;

-- VERDICT: Use BigQuery Agent Analytics Plugin for token tracking


-- ============================================================================
-- 2. TOOL FAILURE RATE ANALYSIS
-- ============================================================================
-- STATUS: PARTIAL - Can detect errors but NOT tool-specific details
-- REASON: OTel logs capture errors but not structured tool events

-- 2a. Count errors by severity (POSSIBLE)
SELECT
  DATE(timestamp) AS date,
  severity,
  COUNT(*) AS count
FROM `test-project-0728-467323.cloud_logging_export.adk_otel_*`
WHERE severity IN ('ERROR', 'WARNING')
  AND timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
GROUP BY date, severity
ORDER BY date DESC, count DESC;

-- 2b. Try to extract tool information (FRAGILE - depends on log format)
SELECT
  timestamp,
  severity,
  -- Best effort extraction from text payload
  REGEXP_EXTRACT(textPayload, r'tool[:\s]+(\w+)') AS maybe_tool_name,
  LEFT(textPayload, 200) AS log_preview
FROM `test-project-0728-467323.cloud_logging_export.adk_otel_*`
WHERE severity = 'ERROR'
  AND timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
ORDER BY timestamp DESC
LIMIT 50;

-- 2c. Tool failure rate (NOT POSSIBLE accurately)
-- REASON: We don't have TOOL_COMPLETED vs TOOL_ERROR event types
-- The BigQuery plugin provides: event_type = 'TOOL_ERROR' vs 'TOOL_COMPLETED'
-- Cloud Logging only has: severity = 'ERROR' (not tool-specific)

-- VERDICT: Use BigQuery Agent Analytics Plugin for accurate tool metrics


-- ============================================================================
-- 3. SESSION AND TRACE ANALYTICS
-- ============================================================================
-- STATUS: PARTIAL - Trace IDs available but no session structure

-- 3a. Count logs by trace (POSSIBLE)
SELECT
  trace,
  COUNT(*) AS log_count,
  MIN(timestamp) AS first_log,
  MAX(timestamp) AS last_log,
  TIMESTAMP_DIFF(MAX(timestamp), MIN(timestamp), SECOND) AS duration_sec
FROM `test-project-0728-467323.cloud_logging_export.adk_otel_*`
WHERE trace IS NOT NULL
  AND timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
GROUP BY trace
ORDER BY log_count DESC
LIMIT 50;

-- 3b. Session analytics (NOT POSSIBLE)
-- REASON: OTel logs don't have session_id field
-- The BigQuery plugin provides: session_id, user_id, invocation_id
-- Cloud Logging only has: trace (which is per-request, not per-session)

SELECT
  -- These fields DON'T EXIST
  JSON_EXTRACT_SCALAR(jsonPayload, '$.session_id') AS session_id,  -- NULL
  JSON_EXTRACT_SCALAR(jsonPayload, '$.user_id') AS user_id,  -- NULL
  JSON_EXTRACT_SCALAR(jsonPayload, '$.invocation_id') AS invocation_id  -- NULL
FROM `test-project-0728-467323.cloud_logging_export.adk_otel_*`
LIMIT 5;

-- VERDICT: Use BigQuery Agent Analytics Plugin for session tracking


-- ============================================================================
-- 4. LATENCY ANALYSIS
-- ============================================================================
-- STATUS: NOT AVAILABLE in logs (only in Cloud Trace spans)
-- REASON: Latency data is in spans, not in log entries

-- The BigQuery plugin captures:
--   - latency_ms.total_ms
--   - latency_ms.time_to_first_token_ms
-- Cloud Logging exports DON'T have this data

-- To get latency from Cloud Trace, you'd need to:
-- 1. Export traces to BigQuery (separate sink)
-- 2. Join logs with traces
-- 3. Parse span duration from trace data

-- This is significantly more complex than the BQ plugin approach

-- VERDICT: Use BigQuery Agent Analytics Plugin for latency metrics


-- ============================================================================
-- 5. MULTI-MODAL CONTENT ANALYSIS
-- ============================================================================
-- STATUS: NOT POSSIBLE
-- REASON: OTel logs don't capture message content or multimodal data

-- The BigQuery plugin captures:
--   - content_parts (images, audio, etc.)
--   - GCS references for large content
--   - MIME types and sizes

-- Cloud Logging has NONE of this

-- VERDICT: Use BigQuery Agent Analytics Plugin for multimodal


-- ============================================================================
-- 6. AI-POWERED ANALYTICS (with Gemini)
-- ============================================================================
-- STATUS: VERY LIMITED
-- REASON: Without structured data, AI analysis is mostly guesswork

-- 6a. Analyze error patterns (POSSIBLE but limited)
SELECT
  timestamp,
  textPayload,
  AI.GENERATE_TEXT(
    MODEL `test-project-0728-467323.cloud_logging_export.gemini_model`,
    CONCAT(
      'Analyze this log entry for issues. What went wrong? ',
      'Log: ', LEFT(COALESCE(textPayload, TO_JSON_STRING(jsonPayload)), 500)
    ),
    STRUCT(0.2 AS temperature, 200 AS max_output_tokens)
  ).ml_generate_text_llm_result AS ai_analysis
FROM `test-project-0728-467323.cloud_logging_export.adk_otel_*`
WHERE severity = 'ERROR'
  AND timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 1 DAY)
ORDER BY timestamp DESC
LIMIT 10;

-- 6b. LLM-as-Judge (NOT POSSIBLE)
-- REASON: Agent responses are NOT captured in OTel logs
-- We can't evaluate what we can't see

-- 6c. Jailbreak Detection (NOT POSSIBLE)
-- REASON: User messages are NOT captured in OTel logs
-- (PII protection: ADK_CAPTURE_MESSAGE_CONTENT_IN_SPANS=false)

-- 6d. Sentiment Analysis (NOT POSSIBLE)
-- REASON: Agent responses are NOT captured

-- 6e. Memory Extraction (NOT POSSIBLE)
-- REASON: Conversation content is NOT captured

-- VERDICT: AI analytics require the BigQuery Agent Analytics Plugin


-- ============================================================================
-- 7. WHAT YOU CAN DO WITH EXPORTED LOGS
-- ============================================================================
-- The following queries ARE useful with exported Cloud Logging data:

-- 7a. Error monitoring dashboard
SELECT
  TIMESTAMP_TRUNC(timestamp, HOUR) AS hour,
  severity,
  COUNT(*) AS count
FROM `test-project-0728-467323.cloud_logging_export.adk_otel_*`
WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 24 HOUR)
GROUP BY hour, severity
ORDER BY hour DESC;

-- 7b. Log volume monitoring
SELECT
  DATE(timestamp) AS date,
  COUNT(*) AS total_logs,
  COUNTIF(severity = 'ERROR') AS errors,
  COUNTIF(severity = 'WARNING') AS warnings
FROM `test-project-0728-467323.cloud_logging_export.adk_otel_*`
WHERE timestamp >= TIMESTAMP_SUB(CURRENT_TIMESTAMP(), INTERVAL 7 DAY)
GROUP BY date
ORDER BY date DESC;

-- 7c. Trace correlation (for debugging)
SELECT
  timestamp,
  severity,
  spanId,
  LEFT(COALESCE(textPayload, TO_JSON_STRING(jsonPayload)), 100) AS preview
FROM `test-project-0728-467323.cloud_logging_export.adk_otel_*`
WHERE trace = 'projects/test-project-0728-467323/traces/YOUR_TRACE_ID'
ORDER BY timestamp;


-- ============================================================================
-- SUMMARY: CAPABILITY COMPARISON
-- ============================================================================
/*
+---------------------------+-------------------+------------------------+
| Capability                | Cloud Log Export  | BQ Analytics Plugin    |
+---------------------------+-------------------+------------------------+
| Token usage               | NOT POSSIBLE      | Full support           |
| Tool success/failure      | Error count only  | Per-tool breakdown     |
| Tool arguments/results    | NOT POSSIBLE      | Full JSON content      |
| Session tracking          | NOT POSSIBLE      | session_id, user_id    |
| Latency metrics           | NOT POSSIBLE      | total_ms, TTFT         |
| Multimodal content        | NOT POSSIBLE      | Full + GCS offload     |
| LLM-as-Judge              | NOT POSSIBLE      | Full support           |
| Jailbreak detection       | NOT POSSIBLE      | Full support           |
| Sentiment analysis        | NOT POSSIBLE      | Full support           |
| Memory extraction         | NOT POSSIBLE      | Full support           |
| Error monitoring          | Basic severity    | Structured events      |
| Trace correlation         | Yes               | Yes + richer context   |
+---------------------------+-------------------+------------------------+

CONCLUSION:
Cloud Logging export to BigQuery provides ~20% of the capabilities
of the BigQuery Agent Analytics Plugin, with 10x the setup effort.

For comprehensive agent analytics, use the BigQuery Agent Analytics Plugin.
*/
