#!/bin/bash
# Documentation Cleanup Script for ADK Security Agent
# Generated by Swarm Execution
# Date: 2025-01-18

echo "🧹 Starting ADK Security Agent Documentation Cleanup..."
echo "================================================"

# Create backup directory
BACKUP_DIR="docs_backup_$(date +%Y%m%d_%H%M%S)"
echo "📦 Creating backup at: $BACKUP_DIR"
mkdir -p "$BACKUP_DIR"

# Define old and new documentation paths
OLD_DOCS="/Users/stuartgano/Desktop/Micron/ADK/contributing/samples/security_agent/docs"
NEW_DOCS="/Users/stuartgano/Desktop/Micron/ADK/contributing/samples/docs"

# Backup existing old documentation
if [ -d "$OLD_DOCS" ]; then
    echo "💾 Backing up existing documentation..."
    cp -r "$OLD_DOCS" "$BACKUP_DIR/"
    echo "✅ Backup completed"
fi

# Files to keep in old location (for reference)
echo "📌 Keeping reference files in original location..."
KEEP_FILES=(
    "ADK_INTEGRATION.md"
    "ADK_DELEGATION_PATTERN_IMPLEMENTATION.md"
    "ADK_SUMMARY.md"
    "ADK_SETUP_GUIDE.md"
    "API_SPECIFICATION.md"
    "DEPLOYMENT_GUIDE.md"
)

# Files to delete (duplicates/obsolete)
echo "🗑️ Marking obsolete files for removal..."
DELETE_FILES=(
    "IMPROVED_ARCHITECTURE_DIAGRAMS.md"
    "CHAT_CENTRIC_ARCHITECTURE.md"
    "GCP_SECURITY_CHAT_ARCHITECTURE.md"
    "PROPOSED_ARCHITECTURE.md"
    "Overall.md"
    "# fixes.md"
    "CHAT_CENTRIC_IMPLEMENTATION_SUMMARY.md"
    "CLEANUP_SUMMARY.md"
)

# Archive obsolete files
ARCHIVE_DIR="$BACKUP_DIR/archived_obsolete"
mkdir -p "$ARCHIVE_DIR"

for file in "${DELETE_FILES[@]}"; do
    if [ -f "$OLD_DOCS/architecture/$file" ]; then
        echo "  Archiving: $file"
        mv "$OLD_DOCS/architecture/$file" "$ARCHIVE_DIR/" 2>/dev/null || true
    fi
done

echo "✅ Obsolete files archived"

# Create symlinks for important reference docs
echo "🔗 Creating reference links..."
REFERENCE_DIR="$NEW_DOCS/reference"
mkdir -p "$REFERENCE_DIR"

for file in "${KEEP_FILES[@]}"; do
    if [ -f "$OLD_DOCS/architecture/$file" ]; then
        ln -sf "$OLD_DOCS/architecture/$file" "$REFERENCE_DIR/$file" 2>/dev/null || true
        echo "  Linked: $file"
    fi
done

echo "✅ Reference links created"

# Summary report
echo ""
echo "📊 Cleanup Summary:"
echo "==================="
echo "✅ Primary BMad documentation created in: $NEW_DOCS"
echo "💾 Backup created at: $BACKUP_DIR"
echo "🔗 Reference docs linked in: $REFERENCE_DIR"
echo "🗑️ Obsolete files archived in: $ARCHIVE_DIR"
echo ""
echo "📝 Next Steps:"
echo "1. Review the cleanup results"
echo "2. Update any remaining code references"
echo "3. Commit the changes to version control"
echo "4. Remove backup after verification"
echo ""
echo "🎉 Documentation cleanup completed successfully!"