#!/usr/bin/env python3
"""
Documentation Automation Suite for ADK Security Agent
Generated by Swarm Execution
Date: 2025-01-18

This script provides automated documentation tasks:
1. Generate API documentation from code
2. Update table of contents
3. Check documentation completeness
4. Generate dependency graphs
"""

import os
import ast
import json
from pathlib import Path
from typing import Dict, List, Any
from datetime import datetime

PROJECT_ROOT = Path("/Users/stuartgano/Desktop/Micron/ADK/contributing/samples")

class DocumentationAutomation:
    """Automated documentation generation and maintenance."""
    
    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.docs_dir = project_root / "docs"
        self.backend_dir = project_root / "security_agent" / "backend"
        self.frontend_dir = project_root / "security_agent" / "frontend"
    
    def generate_api_documentation(self) -> str:
        """Generate API documentation from FastAPI routes."""
        api_docs = []
        api_docs.append("# API Reference")
        api_docs.append(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        
        # Find all API route files
        api_dir = self.backend_dir / "api"
        if api_dir.exists():
            for py_file in api_dir.glob("*.py"):
                if py_file.name == "__init__.py":
                    continue
                
                module_name = py_file.stem
                api_docs.append(f"\n## {module_name.replace('_', ' ').title()}")
                api_docs.append(f"Source: `backend/api/{py_file.name}`\n")
                
                # Parse the file for route definitions
                try:
                    with open(py_file, 'r') as f:
                        tree = ast.parse(f.read())
                    
                    for node in ast.walk(tree):
                        if isinstance(node, ast.FunctionDef):
                            # Check for route decorators
                            for decorator in node.decorator_list:
                                if isinstance(decorator, ast.Attribute):
                                    if decorator.attr in ['get', 'post', 'put', 'delete', 'patch']:
                                        api_docs.append(f"### {decorator.attr.upper()} `{node.name}`")
                                        
                                        # Extract docstring
                                        docstring = ast.get_docstring(node)
                                        if docstring:
                                            api_docs.append(f"{docstring}\n")
                except Exception as e:
                    api_docs.append(f"  Error parsing {py_file.name}: {e}\n")
        
        return "\n".join(api_docs)
    
    def generate_table_of_contents(self) -> str:
        """Generate a table of contents for all documentation."""
        toc = []
        toc.append("# Documentation Table of Contents")
        toc.append(f"Updated: {datetime.now().strftime('%Y-%m-%d')}\n")
        
        # Primary documentation
        toc.append("## 📚 Primary Documentation (BMad Method)\n")
        primary_docs = [
            ("Product Requirements", "prd.md"),
            ("Architecture", "architecture.md"),
            ("Tech Stack", "architecture/tech-stack.md"),
            ("Source Tree", "architecture/source-tree.md"),
            ("Coding Standards", "architecture/coding-standards.md"),
        ]
        
        for title, path in primary_docs:
            full_path = self.docs_dir / path
            if full_path.exists():
                toc.append(f"- [{title}]({path}) ✅")
            else:
                toc.append(f"- [{title}]({path}) ⚠️ Missing")
        
        # Scan for additional documentation
        toc.append("\n## 📁 Additional Documentation\n")
        
        for md_file in self.docs_dir.rglob("*.md"):
            relative = md_file.relative_to(self.docs_dir)
            if str(relative) not in [p for _, p in primary_docs]:
                title = md_file.stem.replace('-', ' ').replace('_', ' ').title()
                toc.append(f"- [{title}]({relative})")
        
        return "\n".join(toc)
    
    def check_documentation_completeness(self) -> Dict[str, Any]:
        """Check if all required documentation exists."""
        report = {
            "complete": [],
            "missing": [],
            "outdated": [],
            "statistics": {}
        }
        
        required_docs = [
            "README.md",
            "docs/prd.md",
            "docs/architecture.md",
            "docs/architecture/tech-stack.md",
            "docs/architecture/source-tree.md",
            "docs/architecture/coding-standards.md",
            "docs/api-reference.md",
            "docs/deployment.md",
            "docs/testing.md",
            "docs/user-guide.md",
        ]
        
        for doc_path in required_docs:
            full_path = self.project_root / doc_path
            if full_path.exists():
                # Check if outdated (older than 30 days)
                mtime = datetime.fromtimestamp(full_path.stat().st_mtime)
                age_days = (datetime.now() - mtime).days
                
                if age_days > 30:
                    report["outdated"].append({
                        "path": doc_path,
                        "age_days": age_days,
                        "last_modified": mtime.strftime('%Y-%m-%d')
                    })
                else:
                    report["complete"].append(doc_path)
            else:
                report["missing"].append(doc_path)
        
        # Calculate statistics
        total = len(required_docs)
        complete = len(report["complete"])
        report["statistics"] = {
            "total_required": total,
            "complete": complete,
            "missing": len(report["missing"]),
            "outdated": len(report["outdated"]),
            "completeness_percentage": round((complete / total) * 100, 2)
        }
        
        return report
    
    def generate_dependency_graph(self) -> str:
        """Generate a mermaid diagram of project dependencies."""
        graph = []
        graph.append("```mermaid")
        graph.append("graph TD")
        graph.append("    %% ADK Security Agent Dependency Graph")
        
        # Define main components
        graph.append("    UI[Streamlit UI]")
        graph.append("    API[FastAPI Backend]")
        graph.append("    ADK[Google ADK]")
        graph.append("    GCP[GCP Services]")
        
        # Define relationships
        graph.append("    UI -->|HTTP/WebSocket| API")
        graph.append("    API -->|Uses| ADK")
        graph.append("    ADK -->|Calls| GCP")
        
        # GCP Services
        graph.append("    GCP -->|Contains| ASSET[Asset Inventory]")
        graph.append("    GCP -->|Contains| IAM[IAM Service]")
        graph.append("    GCP -->|Contains| SEC[Security Center]")
        graph.append("    GCP -->|Contains| LOG[Cloud Logging]")
        
        # Agents
        graph.append("    API -->|Orchestrates| COORD[Coordinator Agent]")
        graph.append("    COORD -->|Delegates| REC[Recognition Agent]")
        graph.append("    COORD -->|Delegates| ASSESS[Assessment Agent]")
        graph.append("    COORD -->|Delegates| DEC[Decision Agent]")
        graph.append("    COORD -->|Delegates| ACT[Action Agent]")
        graph.append("    COORD -->|Delegates| REV[Review Agent]")
        
        graph.append("```")
        
        return "\n".join(graph)
    
    def run_all_automations(self):
        """Run all documentation automation tasks."""
        print("🤖 Running Documentation Automation Suite")
        print("=" * 50)
        
        # 1. Generate API documentation
        print("\n📝 Generating API documentation...")
        api_docs = self.generate_api_documentation()
        api_doc_path = self.docs_dir / "api-reference-auto.md"
        with open(api_doc_path, 'w') as f:
            f.write(api_docs)
        print(f"  ✅ Generated: {api_doc_path}")
        
        # 2. Generate table of contents
        print("\n📚 Generating table of contents...")
        toc = self.generate_table_of_contents()
        toc_path = self.docs_dir / "TABLE_OF_CONTENTS.md"
        with open(toc_path, 'w') as f:
            f.write(toc)
        print(f"  ✅ Generated: {toc_path}")
        
        # 3. Check documentation completeness
        print("\n✅ Checking documentation completeness...")
        report = self.check_documentation_completeness()
        
        print(f"  Complete: {report['statistics']['complete']}/{report['statistics']['total_required']}")
        print(f"  Completeness: {report['statistics']['completeness_percentage']}%")
        
        if report['missing']:
            print(f"\n  ⚠️ Missing documentation:")
            for doc in report['missing']:
                print(f"    - {doc}")
        
        if report['outdated']:
            print(f"\n  📅 Outdated documentation (>30 days):")
            for doc in report['outdated']:
                print(f"    - {doc['path']} ({doc['age_days']} days old)")
        
        # Save report
        report_path = self.docs_dir / "documentation_report.json"
        with open(report_path, 'w') as f:
            json.dump(report, f, indent=2, default=str)
        print(f"\n  📊 Full report saved to: {report_path}")
        
        # 4. Generate dependency graph
        print("\n🔗 Generating dependency graph...")
        graph = self.generate_dependency_graph()
        graph_path = self.docs_dir / "architecture" / "dependency-graph.md"
        graph_path.parent.mkdir(exist_ok=True)
        with open(graph_path, 'w') as f:
            f.write("# System Dependency Graph\n\n")
            f.write(graph)
        print(f"  ✅ Generated: {graph_path}")
        
        print("\n" + "=" * 50)
        print("✅ Documentation automation complete!")
        print("\n📝 Next steps:")
        print("  1. Review generated documentation")
        print("  2. Fill in any missing sections")
        print("  3. Update outdated documentation")
        print("  4. Commit changes to version control")

if __name__ == "__main__":
    automation = DocumentationAutomation(PROJECT_ROOT)
    automation.run_all_automations()