#!/usr/bin/env python3
"""
Update Documentation References in ADK Security Agent Codebase
Generated by Swarm Execution
Date: 2025-01-18
"""

import os
import re
from pathlib import Path
from typing import List, Tuple, Dict

# Define the project root
PROJECT_ROOT = Path("/Users/stuartgano/Desktop/Micron/ADK/contributing/samples")

# Mapping of old paths to new paths
PATH_MAPPINGS = {
    "security_agent/docs/architecture/": "docs/architecture/",
    "security_agent/docs/guides/": "docs/guides/",
    "security_agent/evaluation/README.md": "docs/evaluation.md",
    "security_agent/deploy/README.md": "docs/deployment.md",
    "/architecture/ARCHITECTURE.md": "/architecture.md",
    "/architecture/API_REFERENCE.md": "/architecture/api-reference.md",
}

# File extensions to process
PROCESS_EXTENSIONS = ['.py', '.md', '.yaml', '.yml', '.json', '.txt', '.sh']

def find_files_to_update(root_dir: Path) -> List[Path]:
    """Find all files that might contain documentation references."""
    files_to_update = []
    
    for ext in PROCESS_EXTENSIONS:
        files_to_update.extend(root_dir.rglob(f"*{ext}"))
    
    # Exclude virtual environments and cache directories
    files_to_update = [
        f for f in files_to_update 
        if 'venv' not in str(f) 
        and '__pycache__' not in str(f)
        and '.git' not in str(f)
    ]
    
    return files_to_update

def update_references_in_file(file_path: Path, mappings: Dict[str, str]) -> Tuple[bool, int]:
    """Update documentation references in a single file."""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original_content = content
        changes = 0
        
        # Update each mapping
        for old_path, new_path in mappings.items():
            # Create regex patterns for different reference styles
            patterns = [
                (f"\\[([^\\]]+)\\]\\(([^)]*{re.escape(old_path)}[^)]*)\\)", f"[\\1]({new_path}\\2)"),  # Markdown links
                (f'"{re.escape(old_path)}', f'"{new_path}'),  # Quoted paths
                (f"'{re.escape(old_path)}", f"'{new_path}"),  # Single quoted paths
                (f"\\s{re.escape(old_path)}", f" {new_path}"),  # Space-prefixed paths
            ]
            
            for pattern, replacement in patterns:
                new_content, count = re.subn(pattern, replacement, content)
                if count > 0:
                    content = new_content
                    changes += count
        
        # Write back if changes were made
        if content != original_content:
            with open(file_path, 'w', encoding='utf-8') as f:
                f.write(content)
            return True, changes
        
        return False, 0
    
    except Exception as e:
        print(f"  ❌ Error processing {file_path}: {e}")
        return False, 0

def main():
    """Main execution function."""
    print("🔄 ADK Security Agent - Documentation Reference Updater")
    print("=" * 50)
    
    # Find files to update
    print("\n📂 Scanning for files to update...")
    files = find_files_to_update(PROJECT_ROOT)
    print(f"  Found {len(files)} files to check")
    
    # Update references
    print("\n🔧 Updating documentation references...")
    total_files_updated = 0
    total_changes = 0
    
    for file_path in files:
        updated, changes = update_references_in_file(file_path, PATH_MAPPINGS)
        if updated:
            print(f"  ✅ Updated: {file_path.relative_to(PROJECT_ROOT)} ({changes} changes)")
            total_files_updated += 1
            total_changes += changes
    
    # Summary
    print("\n" + "=" * 50)
    print("📊 Update Summary:")
    print(f"  Files scanned: {len(files)}")
    print(f"  Files updated: {total_files_updated}")
    print(f"  Total changes: {total_changes}")
    
    if total_files_updated > 0:
        print("\n✅ Documentation references updated successfully!")
        print("\n📝 Next steps:")
        print("  1. Review the changes with 'git diff'")
        print("  2. Test that all links still work")
        print("  3. Commit the updates")
    else:
        print("\n✅ No updates needed - all references are current!")

if __name__ == "__main__":
    main()