#!/usr/bin/env python3
"""
Documentation Link Validator for ADK Security Agent
Generated by Swarm Execution
Date: 2025-01-18
"""

import os
import re
from pathlib import Path
from typing import List, Tuple, Set
from collections import defaultdict

PROJECT_ROOT = Path("/Users/stuartgano/Desktop/Micron/ADK/contributing/samples")

def extract_links_from_markdown(file_path: Path) -> List[Tuple[str, str]]:
    """Extract all links from a markdown file."""
    links = []
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # Find markdown links [text](url)
        md_links = re.findall(r'\[([^\]]+)\]\(([^)]+)\)', content)
        
        for text, url in md_links:
            # Skip external URLs
            if url.startswith('http://') or url.startswith('https://'):
                continue
            # Skip anchors
            if url.startswith('#'):
                continue
            links.append((text, url))
        
        # Find reference-style links
        ref_links = re.findall(r'^\[([^\]]+)\]:\s*(.+)$', content, re.MULTILINE)
        for ref, url in ref_links:
            if not url.startswith('http'):
                links.append((ref, url))
    
    except Exception as e:
        print(f"  ❌ Error reading {file_path}: {e}")
    
    return links

def validate_link(base_path: Path, link: str) -> Tuple[bool, str]:
    """Validate if a link points to an existing file."""
    # Clean the link
    link = link.strip()
    if '#' in link:
        link = link.split('#')[0]  # Remove anchor
    
    # Resolve the path
    if link.startswith('/'):
        # Absolute path from project root
        target = PROJECT_ROOT / link.lstrip('/')
    else:
        # Relative path
        target = (base_path.parent / link).resolve()
    
    # Check if file exists
    if target.exists():
        return True, str(target)
    else:
        return False, str(target)

def find_markdown_files(root_dir: Path) -> List[Path]:
    """Find all markdown files in the project."""
    md_files = list(root_dir.rglob("*.md"))
    
    # Exclude virtual environments and backups
    md_files = [
        f for f in md_files 
        if 'venv' not in str(f) 
        and 'backup' not in str(f).lower()
        and '.git' not in str(f)
    ]
    
    return md_files

def main():
    """Main validation function."""
    print("🔍 ADK Security Agent - Documentation Link Validator")
    print("=" * 50)
    
    # Find all markdown files
    print("\n📂 Scanning for documentation files...")
    md_files = find_markdown_files(PROJECT_ROOT)
    print(f"  Found {len(md_files)} markdown files")
    
    # Validate links
    print("\n🔗 Validating documentation links...")
    broken_links = defaultdict(list)
    valid_links = 0
    total_links = 0
    
    for md_file in md_files:
        relative_path = md_file.relative_to(PROJECT_ROOT)
        links = extract_links_from_markdown(md_file)
        
        if links:
            print(f"\n  📄 {relative_path}")
            
            for text, url in links:
                total_links += 1
                is_valid, target_path = validate_link(md_file, url)
                
                if is_valid:
                    valid_links += 1
                    print(f"    ✅ [{text}] -> {url}")
                else:
                    broken_links[str(relative_path)].append((text, url, target_path))
                    print(f"    ❌ [{text}] -> {url} (NOT FOUND)")
    
    # Summary report
    print("\n" + "=" * 50)
    print("📊 Validation Summary:")
    print(f"  Total files checked: {len(md_files)}")
    print(f"  Total links found: {total_links}")
    print(f"  Valid links: {valid_links}")
    print(f"  Broken links: {total_links - valid_links}")
    
    if broken_links:
        print("\n❌ Broken Links Report:")
        print("-" * 30)
        for file, links in broken_links.items():
            print(f"\n📄 {file}:")
            for text, url, target in links:
                print(f"  - [{text}] -> {url}")
                print(f"    Expected at: {target}")
        
        print("\n🔧 To fix broken links:")
        print("  1. Update the link to point to the correct file")
        print("  2. Create the missing documentation file")
        print("  3. Remove the link if no longer needed")
    else:
        print("\n✅ All documentation links are valid!")
    
    # Check for orphaned documents (not linked from anywhere)
    print("\n🔍 Checking for orphaned documents...")
    linked_files = set()
    for md_file in md_files:
        links = extract_links_from_markdown(md_file)
        for _, url in links:
            if not url.startswith('http'):
                linked_files.add(url)
    
    orphaned = []
    for md_file in md_files:
        relative = str(md_file.relative_to(PROJECT_ROOT))
        if relative not in linked_files and 'README' not in relative:
            orphaned.append(relative)
    
    if orphaned:
        print(f"\n📝 Found {len(orphaned)} potentially orphaned documents:")
        for doc in orphaned[:10]:  # Show first 10
            print(f"  - {doc}")
        if len(orphaned) > 10:
            print(f"  ... and {len(orphaned) - 10} more")
    else:
        print("  ✅ No orphaned documents found")

if __name__ == "__main__":
    main()